### ISSUE TITLE
flatRoles breaks /oauth/v2/token endpoint

### ISSUE THREAD

**Issue by chickahoona** [zitadel/actions#13]
I followed this guide here to configure flat roles
https://zitadel.com/blog/custom-claims

copied the custom role from here https://raw.githubusercontent.com/zitadel/actions/main/examples/custom_roles.js

and are now receiving

```
b'{"error":"server_error","error_description":"TypeError: Cannot read property \'count\' of undefined at flatRoles (\\u003ceval\\u003e:2:62(12))"}\n'
```
 

when I call the `https://test-ckfxvq.zitadel.cloud/oauth/v2/token` endpoint. The "Assert Roles on Authentication" is checked as mentioend in the guide. I am using Zitadel Cloud in case someone wants to investigate this.

**Comment by arslan-gait** [comment]
@chickahoona Hi,

I've also faced this error but managed to solve it.
I've changed the line:
```
  if (ctx.v1.user.grants === undefined || ctx.v1.user.grants.count == 0) {
```
to this one:
```
  if (ctx.v1.user.grants === undefined || ctx.v1.user.grants.length == 0) {
```
and everything is working now:
```
...
  "my:zitadel:grants": [
    "208654500901159169:manager"
  ],
...
```

**Comment by chickahoona** [comment]
Sadly doesn't work. Now I am getting an Error 400 with

```
b'{"error":"server_error","error_description":"TypeError: Cannot read property \'length\' of undefined at flatRoles (\\u003ceval\\u003e:2:62(12))"}\n'
```

**Comment by chickahoona** [comment]
I assumed this would only affect so far the only my call to /token under the hood and that Zitadel is using some other endpoints for their login, yet they don't ;) As a result I cannot login anymore to my test environment and had to create a new one, as I always received this:

![image](https://user-images.githubusercontent.com/8075146/232322763-5877c436-433a-4155-ba7c-a262e961283f.png)

**Comment by livio-a** [comment]
the PR #16 will fix the problem (wrong check on undefined)... apologies for the inconvenience 

@chickahoona regarding your test instance: i can temporarily set your action, that it is allowed to fail so you can login again and update the action with the fix.

**Comment by chickahoona** [comment]
That would be great. or just remove that action there or delete the instance. (my whole account is for testing and documentaiton purposes only, so don't be afraid that you by accident delete the wrong isntance ;D)

**Comment by chickahoona** [comment]
I can confirm that the fix works. Thanks alot for your help!
