### ISSUE TITLE
Where are the docs on what api/ctx have available to use?

### ISSUE THREAD

**Issue by kdawgwilk** [zitadel/actions#4]
I have been looking into writing some actions and have been going down a rabbit hole of what I can do with these actions but this repos examples are pretty minimal and don't fully showcase what is available through the ctx/api params passed to the action.

**Comment by fforootd** [comment]
Hi There

I think what you are looking for is located in this pages:

- https://zitadel.com/docs/apis/actions/login-flow
- https://zitadel.com/docs/apis/actions/register-flow

Hope this helps 😁 

Btw. we are constantly expanding the action possibilities, so please let us know if you hit a limitation.

**Comment by kdawgwilk** [comment]
Ah that helps! Thanks!
