### ISSUE TITLE
Simple list of roles

### ISSUE THREAD

**Issue by DebakelOrakel** [zitadel/actions#7]
Hi I want to add a claim to the token using the `Complement Token Flow`, but I dont know how to access the `user grants` object from `ctx`.

**Comment by livio-a** [comment]
Hey @DebakelOrakel 

This is currently not yet possible, but should be soon: https://github.com/zitadel/zitadel/issues/3997

**Comment by DebakelOrakel** [comment]
Ah nice 👍

**Comment by wqdygkd** [comment]
https://zitadel.com/docs/apis/actions/complement-token#parameters-of-pre-userinfo-creation
is this document outdated ?

**Comment by DebakelOrakel** [comment]
Haven't tested it yet, but the PR mentioned above is closed -> Looks like it got implemented.

**Comment by fforootd** [comment]
This should be released with the upcoming 2.22 in roughly a week
